USE fvyvvdbc_productosPila;

-- =====================
-- TABLAS
-- =====================

CREATE TABLE IF NOT EXISTS PRODUCTOS (
	ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL UNIQUE,
	DESCRIPCION VARCHAR(1000) DEFAULT 'undefined',
    CLAVE VARCHAR(50) DEFAULT 'undefined',
    PRESENTACION DOUBLE DEFAULT 0,
    PRESENTACION_UNIDAD VARCHAR(10) DEFAULT 'undefined',
    MARCA VARCHAR(255) DEFAULT 'undefined',
    ID_CATEGORIA INT DEFAULT NULL,
    ID_GRUPO INT DEFAULT NULL,
    INGREDIENTES JSON DEFAULT NULL,
    HISTORIA TEXT DEFAULT NULL,
    IMAGEN_PRODUCTO TEXT DEFAULT NULL,
    ESTADO ENUM('activo', 'inactivo', 'desconocido') NOT NULL DEFAULT 'activo',
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA) ON DELETE SET NULL,
    FOREIGN KEY (ID_GRUPO) REFERENCES GRUPOS (ID_GRUPO) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS CATEGORIAS (
	ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(1000) DEFAULT 'undefined',
    IMAGEN_ETIQUETA TEXT DEFAULT NULL,
	ESTADO ENUM('activo', 'inactivo', 'desconocido') NOT NULL DEFAULT 'activo'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS TABLA_ALIMENTICIA (
	ID_PRODUCTO INT PRIMARY KEY NOT NULL,
	PORCION DOUBLE DEFAULT 0,
    PORCION_UNIDAD VARCHAR(10) DEFAULT 'g',
    CONTENIDO_ENERGETICO DOUBLE DEFAULT 0,
    CONTENIDO_ENERGETICO_UNIDAD VARCHAR(10) DEFAULT 'Kcal',
    PROTEINA DOUBLE DEFAULT 0,
    PROTEINA_UNIDAD VARCHAR(10) DEFAULT 'g',
    GRASAS_TOTALES DOUBLE DEFAULT 0,
    GRASAS_TOTALES_UNIDAD VARCHAR(10) DEFAULT 'g',
    GRASAS_SATURADAS DOUBLE DEFAULT 0,
    GRASAS_SATURADAS_UNIDAD VARCHAR(10) DEFAULT 'g',
    GRASAS_TRANS DOUBLE DEFAULT 0,
    GRASAS_TRANS_UNIDAD VARCHAR(10) DEFAULT 'g',
    CARBOHIDRATOS DOUBLE DEFAULT 0,
    CARBOHIDRATOS_UNIDAD VARCHAR(10) DEFAULT 'g',
    AZUCARES_TOTALES DOUBLE DEFAULT 0,
    AZUCARES_TOTALES_UNIDAD VARCHAR(10) DEFAULT 'g',
    AZUCARES_AÑADIDOS DOUBLE DEFAULT 0,
    AZUCARES_AÑADIDOS_UNIDAD VARCHAR(10) DEFAULT 'g',
    FIBRA_DIETETICA DOUBLE DEFAULT 0,
    FIBRA_DIETETICA_UNIDAD VARCHAR(10) DEFAULT 'g',
    SODIO DOUBLE DEFAULT 0,
    SODIO_UNIDAD VARCHAR(10) DEFAULT 'mg',
    HUMEDAD DOUBLE DEFAULT 0,
    HUMEDAD_UNIDAD VARCHAR(10) DEFAULT '%',
    GRASA_BUTIRICA_MIN DOUBLE DEFAULT 0,
    GRASA_BUTIRICA_MIN_UNIDAD VARCHAR(10) DEFAULT '%',
    PROTEINA_MIN DOUBLE DEFAULT 0,
    PROTEINA_MIN_UNIDAD VARCHAR(10) DEFAULT '%',
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS GRUPOS (
	ID_GRUPO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(1000) DEFAULT 'undefined',
    IMAGEN_ETIQUETA TEXT DEFAULT NULL,
    IMAGEN_BANER TEXT DEFAULT NULL,
	ESTADO ENUM('activo', 'inactivo', 'desconocido') NOT NULL DEFAULT 'activo'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS RECETAS (
	ID_RECETA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(1000) DEFAULT  'undefined',
    INGREDIENTES JSON DEFAULT NULL,
    INSTRUCCIONES JSON DEFAULT NULL,
    TIEMPO_PREPARACION TIME DEFAULT '00:00:00',
    TIEMPO_COCINA TIME DEFAULT '00:00:00',
    ESTADO ENUM('activo', 'inactivo', 'desconocido') NOT NULL DEFAULT 'activo'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS RECETA_PRODUCTO(
    ID_RECETA INT,
    ID_PRODUCTO INT,
    PRIMARY KEY (ID_RECETA, ID_PRODUCTO),
    FOREIGN KEY (ID_RECETA) REFERENCES RECETAS(ID_RECETA) ON DELETE CASCADE,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS CONTACTOS (
	ID_CONTACTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    CORREO_ELECTRONICO VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    DIRECCION_NEGOCIO VARCHAR(1000) DEFAULT 'undefined',
    EMPRESA VARCHAR(500) DEFAULT 'undefined',
    MENSAJE TEXT NOT NULL,
    RFC VARCHAR(50) DEFAULT 'undefined',
    DIRECCION_FISCAL VARCHAR(1000) DEFAULT 'undefined',
    WHATSAPP VARCHAR(20) DEFAULT 'undefined',
    ARCHIVO_ADJUNTO VARCHAR(500) DEFAULT NULL,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    ESTADO ENUM('nuevo', 'leido', 'atendido', 'descartado') NOT NULL DEFAULT 'nuevo'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS COMENTARIOS (
    ID_COMENTARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(200) NOT NULL,
    CORREO_ELECTRONICO VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(20) DEFAULT 'sin telefono',
    DIRECCION VARCHAR(1000) DEFAULT 'sin direccion',
    EMPRESA VARCHAR(500) DEFAULT 'sin empresa',
    MENSAJE TEXT NOT NULL,
    TIPO ENUM('Queja', 'Sugerencia', 'Agradecimiento') NOT NULL,
    ARCHIVO_ADJUNTO VARCHAR(500) DEFAULT NULL,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    ESTADO ENUM('Descartado', 'Pendiente', 'Revisado', 'Resuelto') DEFAULT 'Pendiente'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS SUSCRIPCIONES (
    ID_SUSCRIPCION INT AUTO_INCREMENT PRIMARY KEY,
    CORREO_ELECTRONICO VARCHAR(255) UNIQUE,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO ENUM('Desuscrito', 'Suscrito') DEFAULT 'Suscrito'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- =====================
-- INDICES
-- =====================

-- productos
CREATE INDEX idx_productos_categoria ON PRODUCTOS(ID_CATEGORIA);
CREATE INDEX idx_productos_grupo ON PRODUCTOS(ID_GRUPO);
CREATE INDEX idx_productos_status ON PRODUCTOS(ESTADO);

-- categorias
CREATE INDEX idx_categorias_status ON CATEGORIAS(ESTADO);

-- recetas
CREATE INDEX idx_recetas_status ON RECETAS(ESTADO);

-- receta - productos
CREATE INDEX idx_receta_producto_producto ON RECETA_PRODUCTO(ID_PRODUCTO);
CREATE INDEX idx_receta_producto_receta ON RECETA_PRODUCTO(ID_RECETA);

-- contactos
CREATE INDEX idx_contactos_status ON CONTACTOS(ESTADO);

-- comentarios
CREATE INDEX idx_comentarios_estado ON COMENTARIOS(ESTADO);

-- suscripciones
CREATE INDEX idx_suscripciones_estado ON SUSCRIPCIONES(ESTADO);

-- =====================
-- TRIGGERS
-- =====================

-- productos
DELIMITER $$ -- agegar fila tabla nutrientes

CREATE TRIGGER trg_producto_insert
AFTER INSERT ON PRODUCTOS
FOR EACH ROW
BEGIN
    INSERT INTO TABLA_ALIMENTICIA (ID_PRODUCTO)
    VALUES (NEW.ID_PRODUCTO);
END$$

DELIMITER ;

DELIMITER $$ -- eliminar fila tabla nutrientes

CREATE TRIGGER trg_producto_delete
AFTER DELETE ON PRODUCTOS
FOR EACH ROW
BEGIN
    DELETE FROM TABLA_ALIMENTICIA
    WHERE ID_PRODUCTO = OLD.ID_PRODUCTO;
END$$

DELIMITER ;

-- =====================
-- VIEWS
-- =====================

-- =====================
-- PROCEDURES
-- =====================
