
CREATE TABLE IF NOT EXISTS PRODUCTOS(
    ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    CLAVE VARCHAR(50) DEFAULT 'undefined',
    DESCRIPCION VARCHAR(1000) DEFAULT 'undefined',
    PESO DOUBLE DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;